language: python 
branches:
  except:
  - notebooks
python:
  - "2.7"
# install system dependencies 
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install build-essential
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libnetcdf-dev 
  - sudo apt-get install python-dev
  - sudo apt-get install libgeos-c1 libgeos-dev 
  - sudo apt-get install libatlas-base-dev gfortran
  - sudo apt-get install libblas3gf libc6 libgcc1 libgfortran3 liblapack3gf libumfpack5.4.0 libstdc++6 
# install Python dependencies 
install:
  - sudo pip install conda 
  - sudo conda init 
  - deps='pip numpy scipy matplotlib nose coverage numexpr gdal' 
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION" 
  - export PATH=$HOME/py/bin:$PATH 
  - pip install pycurl
  - pip -v install -r requirements.txt 
script: 
  - nosetests -v --with-coverage --exe
